/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.45.0.
 * To regenerate, run `npx convex dev`.
 */

import type * as erp from "../erp.js";
import type * as excel from "../excel.js";
import type * as imports from "../imports.js";
import type * as reconciliation from "../reconciliation.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  erp: typeof erp;
  excel: typeof excel;
  imports: typeof imports;
  reconciliation: typeof reconciliation;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
