/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.45.0.
 * To regenerate, run `npx convex dev`.
 */

import { anyApi } from "convex/server";

export const api = anyApi;
export const internal = anyApi;
